spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: task123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8001

